Add engilog and update iris

diff --git a/reference/iris b/reference/iris
--- a/reference/iris
+++ b/reference/iris
@@ -1,10 +1,10 @@
-#!/nix/store/561wgc73s0x1250hrgp7jm22hhv7yfln-bash-5.2-p15/bin/bash
+#!/nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash
 
 # ===============================================================
-# iris (0.4.1)
+# iris (1.0.0)
 # Management tool for my systems/nix-config flake.
 #
-# Usage: iris {COMMAND:[(b|build)(e|edit)(n|new)(ls)]} {SYSTEMS:s/h} {CONFIG1} {CONFIG2} --yes --update
+# Usage: iris {COMMAND:[(b|build)(e|edit)(n|new)(ls)(lsgen)(r|revert)]} {SYSTEMS:s/h} {CONFIG1} {CONFIG2} --yes --update
 #
 # Examples:
 # 	iris b sh
@@ -12,6 +12,8 @@
 # 	iris ls
 # 	iris edit
 # 	iris edit h phantom
+# 	iris lsgen sh
+# 	iris r sh 10 30	# reverts system to system generation 10 and home to home generation 30
 # Author: Nathan Martindale
 # License: MIT
 # ===============================================================
@@ -20,7 +22,7 @@ set -o errexit
 set -o nounset
 set -o pipefail
 
-export PATH="/nix/store/zz085nldqpbgvmh9dd39rcq1hxx42m3h-figlet-2.2.5/bin:/nix/store/bv6ym00pq762sbx6qj0w70jzq8r41jf7-nvd-0.2.0/bin:/nix/store/iw0rmgw7hx8ki7hafi0p263i7v9xglbm-lolcat-100.0.1/bin:$PATH"
+export PATH="/nix/store/b1wkn5pr1505kjdlxbcjf2nbhqjpi87q-figlet-2.2.5/bin:/nix/store/fkrm6n9l73bmkihxbmfg5mj9q4b1zk1p-nvd-0.2.0/bin:/nix/store/lhqcxksbqdqw0arqv14f4q2cxsclf0lv-lolcat-100.0.1/bin:/nix/store/gcjdc26g5ihy3n4rainpvi67fn2418bq-ripgrep-13.0.0/bin:/nix/store/hagvhrwy8jzj97kc7nyy9vr18xkg7xvk-jq-1.6-bin/bin:$PATH"
 
 function parse_params() {
   positional_args=()
@@ -38,6 +40,9 @@ function parse_params() {
       -u | --update)
         update=true
         ;;
+      --update-pinned)
+        updatePinned=true
+        ;;
       --version)
         version=true
         ;;
@@ -54,18 +59,21 @@ function parse_params() {
 
 function print_help() {
   echo "Management tool for my systems/nix-config flake."
-  echo -e "\nusage: iris {COMMAND:[(b|build)(e|edit)(n|new)(ls)]} {SYSTEMS:s/h} {CONFIG1} {CONFIG2} --yes --update
+  echo -e "\nusage: iris {COMMAND:[(b|build)(e|edit)(n|new)(ls)(lsgen)(r|revert)]} {SYSTEMS:s/h} {CONFIG1} {CONFIG2} --yes --update
 
 Examples:
 	iris b sh
 	iris build s myconfig
 	iris ls
 	iris edit
-	iris edit h phantom"
+	iris edit h phantom
+	iris lsgen sh
+	iris r sh 10 30	# reverts system to system generation 10 and home to home generation 30"
   echo ""
   echo -e "  -h --help\t\tDisplay this help message."
   echo -e "  -S --sync\t\tSync the nix-config git repository. (This runs before a build step if specified)"
   echo -e "  -u --update\t\tUpdate the flake lock file. (This runs before a build step if specified)"
+  echo -e "  --update-pinned\t\tUpdate the pinned nixpkgs version to the currently locked nixpkgs-unstable. (This runs before a build step if specified)"
   echo -e "  --version\t\tPrint the script version."
   echo -e "  -y --yes\t\tAutomatically apply the (h)ome and/or (s)ystem configuration without prompting."
 }
@@ -79,7 +87,7 @@ if [[ ${help-false} == true ]]; then
 fi
 
 if [[ ${version-false} == true ]]; then
-  echo "0.4.1"
+  echo "1.0.0"
   exit 0
 fi
 
@@ -314,7 +322,7 @@ function build_home() {
 
   # if we've hit this point, we're good to do the build!
   echo "Applying home result..."
-  nix-env --profile "/nix/var/nix/profiles/per-user/${USER}/home-manager" --set ./result-home
+  nix-env --profile "/nix/var/nix/profiles/per-user/${USER}/home-manager" --set ./result-home # TODO: what does this do?
   result-home/activate
   popd &>/dev/null
 }
@@ -330,6 +338,246 @@ function list_system_configs() {
   echo -e "\nAvailable system configurations:"
   # the -P is necessary for grep to handle the parens correctly (perl regex?)
   grep -P ".*\ =\ mk(StableSystem|System)" "${config_location}/flake.nix" | sed -e "s/\s*\([A-Za-z0-9\-\_\@]*\)\ =.*/\1/g"
+}
+
+function list_home_gens() {
+  ensure_config
+  echo -e "\nPrevious clean home generations:"
+  printf "%-5s   %-12s   %-12s\n" "GEN" "GEN DATE" "GIT VERSION"
+  echo "------------------------------------"
+  printf "Collecting...\r"
+  if [[ -e "/nix/var/nix/profiles/per-user/${USER}/home-manager" ]]; then
+    pushd "/nix/var/nix/profiles/per-user/${USER}/" &>/dev/null
+
+    {
+      for filepath in home-manager-*-link; do
+        #echo "${filepath}"
+        # shellcheck disable=SC2001
+        gen_num=$(echo "${filepath}" | sed -e "s/[A-Za-z\-]*\([0-9]*\)/\1/g")
+
+        hm_conf_hash=""
+        hm_conf_revCount=""
+        hm_conf_lastMod=""
+
+        full_path="/nix/var/nix/profiles/per-user/${USER}/${filepath}"
+        if [[ -e "${full_path}/home-files/.local/share/iris/configShortRev" ]]; then
+          hm_conf_hash=$(cat "${full_path}/home-files/.local/share/iris/configShortRev")
+        fi
+        if [[ -e "${full_path}/home-files/.local/share/iris/configRevCount" ]]; then
+          hm_conf_revCount=$(cat "${full_path}/home-files/.local/share/iris/configRevCount")
+          if [[ "${hm_conf_revCount}" == "dirty" ]]; then
+            hm_conf_revCount=""
+          fi
+        fi
+        if [[ -e "${full_path}/home-files/.local/share/iris/configLastModified" ]]; then
+          hm_conf_lastMod=$(cat "${full_path}/home-files/.local/share/iris/configLastModified")
+          if [[ "${hm_conf_lastMod}" != "dirty" ]]; then
+            hm_conf_lastMod=$(date -d "@${hm_conf_lastMod}" +"%Y-%m-%d")
+          fi
+        fi
+        hm_conf_generation_date=$(stat -c %y "/nix/var/nix/profiles/per-user/${USER}/${filepath}")
+        hm_conf_generation_date_time=${hm_conf_generation_date:0:10}
+        if [[ "${hm_conf_revCount}" == "" ]]; then
+          continue
+        fi
+
+        printf "%-5s - %-12s - v%-12s\n" "${gen_num}" "(${hm_conf_generation_date_time})" "${hm_conf_revCount}-${hm_conf_hash}"
+      done
+    } 2>&1 | sort -n | cat
+
+    popd &>/dev/null
+  fi
+}
+
+function list_sys_gens() {
+  ensure_config
+  echo -e "\nPrevious clean system generations:"
+  printf "%-5s   %-12s   %-12s\n" "GEN" "GEN DATE" "GIT VERSION"
+  echo "------------------------------------"
+  printf "Collecting...\r"
+  if [[ -e "/nix/var/nix/profiles/system" ]]; then
+    pushd "/nix/var/nix/profiles/" &>/dev/null
+
+    {
+      for filepath in system-*-link; do
+        #echo "${filepath}"
+        # shellcheck disable=SC2001
+        gen_num=$(echo "${filepath}" | sed -e "s/[A-Za-z\-]*\([0-9]*\)/\1/g")
+
+        system_hash=""
+        system_revCount=""
+        system_lastMod=""
+
+        full_path="/nix/var/nix/profiles/${filepath}"
+        if [[ -e "${full_path}/etc/iris/configShortRev" ]]; then
+          system_hash=$(cat "${full_path}/etc/iris/configShortRev")
+        fi
+        if [[ -e "${full_path}/etc/iris/configRevCount" ]]; then
+          system_revCount=$(cat "${full_path}/etc/iris/configRevCount")
+          if [[ "${system_revCount}" == "dirty" ]]; then
+            system_revCount=""
+          fi
+        fi
+        if [[ -e "${full_path}/etc/iris/configLastModified" ]]; then
+          system_lastMod=$(cat "${full_path}/etc/iris/configLastModified")
+          if [[ "${system_lastMod}" != "dirty" ]]; then
+            system_lastMod=$(date -d "@${system_lastMod}" +"%Y-%m-%d")
+          fi
+        fi
+        system_generation_date=$(stat -c %y "/nix/var/nix/profiles/${filepath}")
+        system_generation_date_time=${system_generation_date:0:10}
+        if [[ "${system_revCount}" == "" ]]; then
+          continue
+        fi
+
+        printf "%-5s - %-12s - v%-12s\n" "${gen_num}" "(${system_generation_date_time})" "${system_revCount}-${system_hash}"
+      done
+    } 2>&1 | sort -n | cat
+
+    popd &>/dev/null
+  fi
+}
+
+function activate_previous_home_gen() {
+  # NOTE: expects to be passed a string number
+  ensure_config
+  echo -e "\nRe-activiating previous home generation ${1}..."
+
+  if [[ -e "/nix/var/nix/profiles/per-user/${USER}/home-manager-${1}-link" ]]; then
+
+    nvd diff "/nix/var/nix/profiles/per-user/${USER}/home-manager" "/nix/var/nix/profiles/per-user/${USER}/home-manager-${1}-link"
+
+    if [[ ${yes-false} == false ]]; then
+      # prompt loop
+      valid_response=false
+      while [[ ${valid_response} == false ]]; do
+        read -r -p "Apply previous home generation result? [Y/n]" response
+        case "${response}" in
+          [nN][oO] | [nN])
+            echo "Previous home generation not applied."
+            return
+            ;;
+          [yY][eE][sS] | [yY])
+            valid_response=true
+            break
+            ;;
+          "")
+            valid_response=true
+            break
+            ;;
+          *)
+            echo "Invalid response, please enter [y]es or [n]o."
+            ;;
+        esac
+      done
+    fi
+
+    echo "Applying home generation ${1}..."
+    # shellcheck disable=SC1090
+    . "/nix/var/nix/profiles/per-user/${USER}/home-manager-${1}-link/activate"
+  else
+    echo "Could not find generation, use the 'iris lsgen' command to list valid generation numbers."
+    exit 1
+  fi
+}
+
+function activate_previous_sys_gen() {
+  # NOTE: expects to be passed a string number
+  ensure_config
+  echo -e "\nRe-activiating previous system generation ${1}..."
+
+  if [[ -e "/nix/var/nix/profiles/system-${1}-link" ]]; then
+
+    nvd diff "/nix/var/nix/profiles/system" "/nix/var/nix/profiles/system-${1}-link"
+
+    if [[ ${yes-false} == false ]]; then
+      # prompt loop
+      valid_response=false
+      while [[ ${valid_response} == false ]]; do
+        read -r -p "Apply previous system result? [Y/n]" response
+        case "${response}" in
+          [nN][oO] | [nN])
+            echo "Previous system generation not applied."
+            return
+            ;;
+          [yY][eE][sS] | [yY])
+            valid_response=true
+            break
+            ;;
+          "")
+            valid_response=true
+            break
+            ;;
+          *)
+            echo "Invalid response, please enter [y]es or [n]o."
+            ;;
+        esac
+      done
+    fi
+
+    echo "Applying system generation ${1}..."
+    # shellcheck disable=SC1090
+    . "/nix/var/nix/profiles/system-${1}-link/activate"
+  else
+    echo "Could not find generation, use the 'iris lsgen' command to list valid generation numbers."
+    exit 1
+  fi
+}
+
+function update_pinned_nixpkgs() {
+  # finds out the current rev of nixpkgs-unstable in local flake lock,
+  # then modifies flake nixpkgs-pinned to that rev, after ensuring pinned
+  # isn't already in use anywhere
+  ensure_config
+
+  # make sure we're not using pinned somewhere
+  echo -e "\nChecking for existing pinned package usage..."
+  pushd "${config_location}" &>/dev/null
+  found=false
+
+  # check in the home configs
+  pushd home &>/dev/null
+  if rg "pinned\."; then
+    found=true
+  fi
+  popd &>/dev/null
+
+  # check in the nixos system configs
+  pushd hosts &>/dev/null
+  if rg "pinned\."; then
+    found=true
+  fi
+  popd &>/dev/null
+
+  if [[ ${found} == true ]]; then
+    echo "WARNING: existing uses of pinned packages found, updating pinned channel before changing these could lead to unintended breakages!"
+    # prompt loop
+    valid_response=false
+    while [[ ${valid_response} == false ]]; do
+      read -r -p "Update nixpkgs-pinned anyway? [y/n]" response
+      case "${response}" in
+        [nN][oO] | [nN])
+          echo "Not updating pinned nixpkgs."
+          exit 1
+          ;;
+        [yY][eE][sS] | [yY])
+          valid_response=true
+          break
+          ;;
+        *)
+          echo "Invalid response, please enter [y]es or [n]o."
+          ;;
+      esac
+    done
+  fi
+
+  # get current nixpkgs-unstable revision
+  unstableRevision=$(jq -r '.nodes."nixpkgs-unstable"'.locked.rev flake.lock)
+
+  echo "Updating flake pinned nixpkgs to revision ${unstableRevision}"
+  # change the flake.nix (danger!)
+  sed -i -E "s/nixpkgs\-pinned.url\ =\ .*\;\$/nixpkgs\-pinned.url\ =\ \"github:nixos\/nixpkgs?rev=${unstableRevision}\";/" flake.nix
+  popd &>/dev/null
 }
 
 function open_for_edit() {
@@ -355,6 +603,13 @@ collect_and_print_info
 
 if [[ ${sync-false} == true ]]; then
   sync_repo
+fi
+
+# NOTE: we have to run update-pinned before a regular update!
+# this allows us to both update pinned and the regular nixpkgs-unstable
+# without changing them both to the same latest nixpkgs-unstable
+if [[ ${updatePinned--false} == true ]]; then
+  update_pinned_nixpkgs
 fi
 
 if [[ ${update-false} == true ]]; then
@@ -480,8 +735,60 @@ if [[ $# -gt 0 ]]; then
           ;;
       esac
       ;;
+    lsgen)
+      case "${config_types}" in
+        hs | sh | "")
+          list_home_gens
+          list_sys_gens
+          ;;
+        h)
+          list_home_gens
+          ;;
+        s)
+          list_sys_gens
+          ;;
+        *)
+          echo "Invalid config types, please specify 'h' and/or 's'"
+          exit 1
+          ;;
+      esac
+      ;;
+    r | revert)
+      if [[ "${config1}" == "" ]]; then
+        echo "Please specify a generation number to revert to."
+        exit 1
+      fi
+      case "${config_types}" in
+        sh)
+          if [[ "${config2}" == "" ]]; then
+            echo "Please specify both generation numbers to revert to."
+            exit 1
+          fi
+          activate_previous_home_gen "${config2}"
+          activate_previous_sys_gen "${config1}"
+          ;;
+        hs)
+          if [[ "${config2}" == "" ]]; then
+            echo "Please specify both generation numbers to revert to."
+            exit 1
+          fi
+          activate_previous_home_gen "${config1}"
+          activate_previous_sys_gen "${config2}"
+          ;;
+        h)
+          activate_previous_home_gen "${config1}"
+          ;;
+        s)
+          activate_previous_sys_gen "${config1}"
+          ;;
+        *)
+          echo "Invalid config types, please specify 'h' and/or 's'"
+          exit 1
+          ;;
+      esac
+      ;;
     *)
-      echo "Invalid command, please specify [b|build]|[e|edit]|[n|new]|ls"
+      echo "Invalid command, please specify [b|build]|[e|edit]|[n|new]|[r|revert]|ls|lsgen"
       exit 1
       ;;
   esac
